--[[ ----------------------------------------------------------------------------------------------
 File       : dialog_stancia.script
 Description: Dialog & InfoPortions Function for stancia
 Copyright  : 2011 © LA
 Author     : lox
 Editors    : lox, vintar
 Last edit  : 06.08.2012 (by ...)
--]] ----------------------------------------------------------------------------------------------
local log = function(fmt, ...) _G.log(script_name()..":"..tostring(fmt), ...) end
--/ ------------------------------------------------------------------
--/ Process
--/ ------------------------------------------------------------------
function aes_give_rpg(first, second)
	dialogs.give_items("wpn_rpg7", 1)
	dialogs.give_items("ammo_og-7b", 4)
end

function give_tranceiver(first, second)
	dialogs.give_items("tranceiver", 1)
end

function aes_dudaev_dead()
	return has_info("aes_dudaev_dead")
end
--/ -----------------------------------------------------------------------------------------------