
-- barin, last update: 2010-08-08
local log = function(fmt, ...) _G.log(script_name(), tostring(fmt), ...) end
function load_job(sj, gname, type, squad, groups)
end

function load_states(gname, type)
end

function load_ltx(gname, type)
	return nil
end

function checkStalker(npc_community, gulag_type, npc_rank, se_obj)
	return false
end

function checkMonster(npc_community, gulag_type)
	return false
end
