--[[ ----------------------------------------------------------------------------------------------
 File       : gulag_labx7.script
 Description: Gulags labx7
 Copyright  : 2004 © LA-team
 Author     : loxotron
 Editors    : loxotron(23.02.2013)
 Last edit  : 26.02.2013 (by ...) [...]
--]] ----------------------------------------------------------------------------------------------

--/ -----------------------------------------------------------------
local sModule = script_name()
--/ -----------------------------------------------------------------
local log = function(fmt,...) _G.log(sModule..":"..tostring(fmt),...) end
--/ -----------------------------------------------------------------------------------------------
--/ General VARIABLEs
--/ -----------------------------------------------------------------------------------------------
local gulags = {
	--/ for stalkers ------------------------------
	--/ for monsters ------------------------------
	bas_zombies_smart  = {comm = {"zombie"}},
	bas_zombies_smart2 = {comm = {"zombie"}},
	bas_pseudo_smart   = {comm = {"pseudodog"}},
}
--/ -----------------------------------------------------------------
--/ Process
--/ -----------------------------------------------------------------
function getGulag(gtype)
	return gulags[gtype] --/>
end
--/ ----------------------------------------------
local on_level_pred = function(info,gulag) return xr_gulag.is_on_gulag_level(info.se_obj,gulag) end
--/------------------------------------------------------------------------------------------------
--/ Gulags
--/------------------------------------------------------------------------------------------------
--/ zombies
--/ ---------------------------------------------
gulags.bas_zombies_smart.jobs = function(sj, gname, type, squad, groups)
	gulags.bas_zombies_smart.ltx = smart_dyn_ltx.add_fake_home(type, 4, 5, 7)
	
	table.insert(sj, gulag_tasks.getJob("fake_death1", 0, 5, {0}, squad, groups[1], "", "", false, type, on_level_pred))
	table.insert(sj, gulag_tasks.getJob("fake_death2", 0, 5, {0}, squad, groups[1], "", "", false, type, on_level_pred))
	table.insert(sj, gulag_tasks.getJob("fake_death3", 0, 5, {1}, squad, groups[1], "", "",   nil, type, on_level_pred))
	table.insert(sj, gulag_tasks.getJob("fake_death4", 0, 5, {1}, squad, groups[1], "", "",   nil, type, on_level_pred))
end

gulags.bas_zombies_smart.state = function(gulag)
	if has_info("bas_switcher_off") then
		return 1
	end
	return 0
end

--/ ---------------------------------------------
gulags.bas_zombies_smart2.jobs = function(sj, gname, type, squad, groups)
	for i = 1, 2 do
		table.insert(sj, gulag_tasks.getJob("home" .. i, 0, 5, {0}, squad, groups[1], "", "", false, type, on_level_pred))
	end
	for i = 3, 4 do
		table.insert(sj, gulag_tasks.getJob("home" .. i, 0, 5, {1}, squad, groups[1], "", "",   nil, type, on_level_pred))
	end
end

gulags.bas_zombies_smart2.state = function(gulag)
	if has_info("bas_cs2_end") then
		return 1
	end
	return 0
end

--/ ---------------------------------------------
--/ pseudodogs
--/ ---------------------------------------------
gulags.bas_pseudo_smart.jobs = function(sj, gname, type, squad, groups)
	gulags.bas_pseudo_smart.ltx = smart_dyn_ltx.add_mob_home(type, 6, 5, 8)
	
	for i = 1, 3 do
		table.insert(sj, gulag_tasks.getJob("home" .. i, 0, 5, {0}, squad, groups[1], "", "", false, type, on_level_pred))
	end
	for i = 4, 6 do
		table.insert(sj, gulag_tasks.getJob("home" .. i, 0, 5, {1}, squad, groups[1], "", "",   nil, type, on_level_pred))
	end
end

gulags.bas_pseudo_smart.state = function(gulag)
	if has_info("bas_sc6_finale") then
		return 1
	end
	return 0
end
--/ ------------------------------------------------------------------------------------------------