--[[-----------------------------------------------------------------------------------------------
 File       : mob_sound.script
 Description: "Îçâó÷êà ìîíñòğîâ"
 Copyright  : 2004 © GSC Game World
 Author     : Andrey Fidrya (Zmey) af@svitonline.com (Èñõîäíûé ñêğèïò (trader): Evgeniy Negrobov (Jon) jon@gsc-game.kiev.ua)
 Editors    : ...
 Last edit  : 05.04.2013 [...]
--]]-----------------------------------------------------------------------------------------------
--/NOTE: Îçâó÷êà òîğãîâöà ïåğåíåñåíà â 'xr_trader.script'
--/      The postscoring of the trader(s) is transferred to 'xr_trader.script'
--/ ------------------------------------------------------------------
--/ ------------------------------------------------------------------
--/ VARIABLEs
--/ ------------------------------------------------------------------
local tSounds = {
	gen_bloodsucker_eat  = { "monsters\\bloodsucker\\eat_0" },
	gen_bloodsucker_idle = { "monsters\\bloodsucker\\idle_0" },
	mil_controller_call  = { "characters_voice\\scenario\\mil\\mil_controller_call" }
}
--/ --------------------------
local sModule = script_name()
--/ ------------------------------------------------------------------
local log = function(fmt, ...) _G.log(sModule..":"..tostring(fmt), ...) end
--/ ------------------------------------------------------------------
--/ Process
--/ ------------------------------------------------------------------
function pick_sound_from_set(oNPC, sSetSnd, tLastSoundInfo)
	local tSetSnd = sSetSnd and tSounds[sSetSnd]
	if tSetSnd then
		--/ Âûáèğàåì ñëó÷àéíûé çâóê èç íàáîğà: tSetSnd
		local sSndPicked = nil
		local iChance = 1
		for k,v in pairs(tSetSnd) do
			if math.random(iChance) == 1 then
				sSndPicked = v
			end
			iChance = iChance +1
		end
		return sSndPicked --/>
	end
	return nil --/>
end
--/ -----------------------------------------------------------------------------------------------