--[[ ----------------------------------------------------------------------------------------------
 File       : sound_theme.script
 Description: Схема озвучки
 Copyright  : 2004 © GSC Game World
 Author     : автор: Диденко Руслан (Stohe), update: Чугай Александр (Chugai)
 Last edit  : 16.08.2013 [gr1ph00n]
--]] ----------------------------------------------------------------------------------------------

--/------------------------------------------------------------------
--/ VARIABLEs
--/------------------------------------------------------------------
snd_ini = ini_file("misc\\script_sound.ltx")
nstl = 64
sound_mask = 1
sound_priority = 2
--/ --------------------------
local sModule = script_name()
--/ -----------------------------------------------------------------
local log = function(fmt,...) _G.log(sModule..":"..tostring(fmt),...) end
--/ -----------------------------------------------------------------------------------------------
ph_snd_themes = { --/ таблица звуков физ.объектов (предметов)
--/ -----------------------------------------------------------------------------------------------
	rock = {"script_replics\\magnitofon\\rock"},
	cheeki_breeki = {"script_replics\\megafon\\music\\bandits_radio"},
	sid_radio = {
		"script_replics\\magnitofon\\magnitofon_1",
                "script_replics\\magnitofon\\magnitofon_2",
                "script_replics\\magnitofon\\magnitofon_3",
				"script_replics\\magnitofon\\magnitofon_4",
                "script_replics\\magnitofon\\magnitofon_5",
	},
	bar_transiever = {
		"script_replics\\radio\\message\\radio_voice_1",
		"script_replics\\radio\\message\\radio_noise_1",
		"script_replics\\radio\\message\\radio_voice_2",
		"script_replics\\radio\\message\\radio_noise_2",
		"script_replics\\radio\\message\\radio_voice_3",
	},
	old_radio_music = {
		"script_replics\\magnitofon\\magnitofon_1",
		"script_replics\\magnitofon\\magnitofon_2",
		"script_replics\\magnitofon\\magnitofon_3",
		"script_replics\\magnitofon\\magnitofon_4",
		"script_replics\\magnitofon\\magnitofon_5",
	},
	music = {
		"script_replics\\megafon\\music\\megafon_music_1",
		"script_replics\\megafon\\music\\megafon_music_2",
		"script_replics\\megafon\\music\\megafon_music_3",
		"script_replics\\megafon\\music\\megafon_music_4",
		"script_replics\\megafon\\music\\megafon_music_5",
		"script_replics\\megafon\\music\\megafon_music_6",
		"script_replics\\megafon\\music\\megafon_music_7",
		"script_replics\\megafon\\music\\megafon_music_8",
		"script_replics\\megafon\\music\\megafon_music_9",
		"script_replics\\megafon\\music\\megafon_music_10",
		"script_replics\\megafon\\music\\megafon_music_11",
		"script_replics\\megafon\\music\\megafon_music_12",
		"script_replics\\megafon\\music\\megafon_music_13",
		"script_replics\\megafon\\music\\megafon_music_14",
		"script_replics\\megafon\\music\\megafon_music_15",
	},
	bas_bad_music = {"characters_voice\\scenario\\bas\\bas_bad_music"},
	bas_kolaska   = {"characters_voice\\scenario\\bas\\bas_karusel"},
	humor = {
		"script_replics\\megafon\\comandir\\comandir_megafon_1",
		"script_replics\\megafon\\comandir\\comandir_megafon_2",
		"script_replics\\megafon\\comandir\\comandir_megafon_3",
		"script_replics\\megafon\\comandir\\comandir_megafon_4",
		"script_replics\\megafon\\comandir\\comandir_megafon_5",
	},
	humor_soc = {
			"characters_voice\\scenario\\escape\\comandir_megafon_1",
		"characters_voice\\scenario\\escape\\comandir_megafon_2",
		"characters_voice\\scenario\\escape\\comandir_megafon_3",
		"characters_voice\\scenario\\escape\\comandir_megafon_4",
		"characters_voice\\scenario\\escape\\comandir_megafon_5",
		"characters_voice\\scenario\\escape\\comandir_megafon_6",
		"characters_voice\\scenario\\escape\\comandir_megafon_7",
		"characters_voice\\scenario\\escape\\comandir_megafon_8",
		"characters_voice\\scenario\\escape\\comandir_megafon_9",
		"characters_voice\\scenario\\escape\\comandir_megafon_10",
		"characters_voice\\scenario\\escape\\comandir_megafon_11",
		"characters_voice\\scenario\\escape\\comandir_megafon_12",
		"characters_voice\\scenario\\escape\\comandir_megafon_13",
		"characters_voice\\scenario\\escape\\comandir_megafon_14",
		"characters_voice\\scenario\\escape\\comandir_megafon_15",
		"characters_voice\\scenario\\escape\\comandir_megafon_16",
		"characters_voice\\scenario\\escape\\comandir_megafon_17",
	},
	epic = {
		"characters_voice\\scenario\\escape\\megafon_1",
		"characters_voice\\scenario\\escape\\megafon_2",
		"characters_voice\\scenario\\escape\\megafon_3",
		"characters_voice\\scenario\\escape\\megafon_4",
	},
	alarm1 = {
		"script_replics\\megafon\\alarm\\megafon_alarm_1",
		"script_replics\\megafon\\alarm\\megafon_alarm_10",
		"script_replics\\megafon\\alarm\\megafon_alarm_11",
		"script_replics\\megafon\\alarm\\megafon_alarm_12",
		"script_replics\\megafon\\alarm\\megafon_alarm_13",
	},
	alarm2 = {
		"script_replics\\megafon\\alarm\\megafon_alarm_2",
		"script_replics\\megafon\\alarm\\megafon_alarm_3",
		"script_replics\\megafon\\alarm\\megafon_alarm_4",
		"script_replics\\megafon\\alarm\\megafon_alarm_5",
		"script_replics\\megafon\\alarm\\megafon_alarm_6",
		"script_replics\\megafon\\alarm\\megafon_alarm_7",
		"script_replics\\megafon\\alarm\\megafon_alarm_8",
		"script_replics\\megafon\\alarm\\megafon_alarm_9",
	},
	siren          = { "ambient\\siren2" },
	siren_1        = { "ambient\\siren1" },
	siren_2        = { "ambient\\siren2" },
	dar_alarm      = { "scripts\\alarm\\l_alarm" },
	war_laser_loop = { "characters_voice\\scenario\\war\\war_laser_loop" },
	bomb           = {"detectors\\bomb_timer"},
	detector       = {"detectors\\da-2_beep1"},
	dar_scary = {
		"characters_voice\\scenario\\dar\\dar_scary_1",
		"characters_voice\\scenario\\dar\\dar_scary_2",
		"characters_voice\\scenario\\dar\\dar_scary_3",
	},
	radio_music = {"characters_voice\\scenario\\bar\\radio_music\\radio_music_1"},
	dolg_speech = {
		"characters_voice\\scenario\\bar\\barman_megafon\\megaphone_barman_1",
		"characters_voice\\scenario\\bar\\barman_megafon\\megaphone_barman_2",
		"characters_voice\\scenario\\bar\\dolg_megafon\\mega_duty_propaganda_1",
		"characters_voice\\scenario\\bar\\dolg_megafon\\mega_duty_propaganda_2",
		"characters_voice\\scenario\\bar\\dolg_megafon\\mega_duty_propaganda_3",
		"characters_voice\\scenario\\bar\\dolg_megafon\\mega_duty_propaganda_4",
		"characters_voice\\scenario\\bar\\dolg_megafon\\mega_duty_propaganda_5",
		"characters_voice\\scenario\\megafon\\megafon_music_1",
		"characters_voice\\scenario\\megafon\\megafon_music_2",
		"characters_voice\\scenario\\megafon\\megafon_music_3"
	},
	dolg_alarm         = {"characters_voice\\scenario\\bar\\dolg_megafon\\megaphone_duty_alarm"},
	dolg_megafon_1_hit = {"characters_voice\\scenario\\bar\\dolg_megafon\\duty_gunfire_mega_1"},
	dolg_megafon_2_hit = {"characters_voice\\scenario\\bar\\dolg_megafon\\duty_gunfire_mega_2"},
	dolg_megafon_kill  = {"characters_voice\\scenario\\bar\\dolg_megafon\\duty_gunfire_mega_3"},
	arena_introduce_pseudodog   = {"characters_voice\\scenario\\bar\\arena_megafon\\mega_arena_pseudodog"},
	arena_introduce_snork       = {"characters_voice\\scenario\\bar\\arena_megafon\\mega_arena_snork"},
	arena_introduce_bloodsucker = {"characters_voice\\scenario\\bar\\arena_megafon\\mega_arena_bloodsucker"},
	arena_introduce_burer       = {"characters_voice\\scenario\\bar\\arena_megafon\\mega_arena_burer"},
	arena_introduce_savage      = {"characters_voice\\scenario\\bar\\arena_megafon\\mega_arena_zver"},
	arena_actor_afraid          = {"characters_voice\\scenario\\bar\\arena_megafon\\mega_arena_coward"},
	arena_fight_begin           = {"characters_voice\\scenario\\bar\\arena_megafon\\mega_arena_start"},
	arena_fight_victory         = {"characters_voice\\scenario\\bar\\arena_megafon\\mega_arena_win_1"},
	arena_fight_victory_notime  = {"characters_voice\\scenario\\bar\\arena_megafon\\mega_arena_win_2"},
	arena_fight_lose            = {"characters_voice\\scenario\\bar\\arena_megafon\\mega_arena_out_of_time_win"},
	arena_fight_death           = {"characters_voice\\scenario\\bar\\arena_megafon\\mega_arena_dead"},
	bar_start_megafon = {
		"characters_voice\\scenario\\bar\\barman_megafon\\megaphone_barman_1",
		"characters_voice\\scenario\\bar\\barman_megafon\\megaphone_barman_2",
		"characters_voice\\scenario\\bar\\dolg_megafon\\mega_duty_propaganda_1",
		"characters_voice\\scenario\\bar\\dolg_megafon\\mega_duty_propaganda_2"
	},
	mon_monolith_damaged       = {"characters_voice\\scenario\\sarcofag\\monolith_damaged"},
	mon_monolith_heavy_damaged = {"characters_voice\\scenario\\sarcofag\\monolith_heavy_damaged"},
	mon_monolith_alarm         = {"characters_voice\\scenario\\sarcofag\\monolith_alarm"},
	mon_monolith_recharged     = {"characters_voice\\scenario\\sarcofag\\monolith_recharged"},
	sar_monolith_call = {
		"characters_voice\\scenario\\sarcofag\\monolith_call_1",
		"characters_voice\\scenario\\sarcofag\\monolith_call_2",
		"characters_voice\\scenario\\sarcofag\\monolith_call_3",
		"characters_voice\\scenario\\sarcofag\\monolith_call_4",
		"characters_voice\\scenario\\sarcofag\\monolith_call_5",
		"characters_voice\\scenario\\sarcofag\\monolith_call_6",
		"characters_voice\\scenario\\sarcofag\\monolith_call_7"
	},
	sar_theme = {
		"music\\sar_theme_l",
		"music\\sar_theme_r"
	},
	aes_battle1          = {"ambient\\battle_1"},
	aes_battle2          = {"ambient\\battle_2"},
	gar_seryi_shooting   = {"characters_voice\\scenario\\garbage\\distance_shooting"},
	gar_seryi_shooting_2 = {"characters_voice\\scenario\\bandits\\bandit_replic_2"},
	gar_bandits_seryi    = {
		"characters_voice\\scenario\\garbage\\grey_bandit_1",
		"characters_voice\\scenario\\garbage\\grey_bandit_2",
		"characters_voice\\scenario\\garbage\\grey_bandit_3",
		"characters_voice\\scenario\\garbage\\grey_bandit_4",
		"characters_voice\\scenario\\garbage\\grey_bandit_5"
	},
	radar_drone   = {"ambient\\radar_1"},
	radar_thunder = {"ambient\\radar_2"},
	radar_sparks  = {"ambient\\radarsparks_1"},
	aes_teleport  = {"anomaly\\teleport_incoming"},
	radar_meh_on  = {"ambient\\cooling_run"},
	radar_meh_off = {"ambient\\cooling_stop"},
	agro_test     = {"weapons\\grenade1"},
	system_message_1 = {"characters_voice\\scenario\\yantar\\system_message_1"},
	system_message_2 = {"characters_voice\\scenario\\yantar\\system_message_2"},
	system_message_3 = {"characters_voice\\scenario\\yantar\\system_message_3"},
	system_message_4 = {"characters_voice\\scenario\\yantar\\system_message_4"},
	system_message_5 = {"characters_voice\\scenario\\yantar\\system_message_5"},
	bar_arena_public = {
		"characters_voice\\scenario\\bar\\arena_public\\new_arena_public_1",
		"characters_voice\\scenario\\bar\\arena_public\\new_arena_public_1",
		"characters_voice\\scenario\\bar\\arena_public\\new_arena_public_2",
		"characters_voice\\scenario\\bar\\arena_public\\new_arena_public_3",
		"characters_voice\\scenario\\bar\\arena_public\\new_arena_public_4",
		"characters_voice\\scenario\\bar\\arena_public\\new_arena_public_5",
		"characters_voice\\scenario\\bar\\arena_public\\new_arena_public_6",
		"characters_voice\\scenario\\bar\\arena_public\\new_arena_public_7",
		"characters_voice\\scenario\\bar\\arena_public\\new_arena_public_8",
		"characters_voice\\scenario\\bar\\arena_public\\new_arena_public_9"
	},
	bar_arena_public_start = {"ambient\\arena\\crowd_new"},
	bar_arena_public_start_savage = {
		"ambient\\arena\\crowd_new2",
		"ambient\\arena\\crowd_new3"
	},
	bar_arena_public_death = {
		"ambient\\arena\\crowd_wave_1",
		"ambient\\arena\\crowd_wave_2",
		"ambient\\arena\\crowd_wave_3"
	},
	bar_arena_fight_1     = {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_1_ready"},
	bar_arena_fight_1_end = {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_1_finish"},
	bar_arena_fight_2     = {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_2_ready"},
	bar_arena_fight_2_end = {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_2_finish"},
	bar_arena_fight_3     = {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_3_ready"},
	bar_arena_fight_3_end = {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_3_finish"},
	bar_arena_fight_4     = {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_4_ready"},
	bar_arena_fight_4_end = {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_4_finish"},
	bar_arena_fight_5     = {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_5_ready"},
	bar_arena_fight_5_end = {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_5_finish"},
	bar_arena_fight_6     = {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_6_ready"},
	bar_arena_fight_6_end = {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_6_finish"},
	bar_arena_fight_7     = {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_7_ready"},
	bar_arena_fight_7_end = {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_7_finish"},
	bar_arena_fight_8     = {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_8_ready"},
	bar_arena_fight_8_end = {"characters_voice\\scenario\\bar\\arena_sound\\bar_fight_8_finish"},
	x18_sound_1  = {"ambient\\x18\\x18_hit_8"},
	x18_sound_2  = {"ambient\\x18\\x18_metal_2"},
	x18_sound_3  = {"ambient\\x18\\x18_metal_3"},
	x18_sound_4  = {"ambient\\x18\\x18_metal_4"},
	x18_sound_5  = {"ambient\\x18\\x18_metal_5"},
	x18_sound_6  = {"ambient\\x18\\x18_creak_2"},
	x18_sound_7  = {"ambient\\x18\\x18_creak_1"},
	x18_sound_8  = {"ambient\\x18\\x18_hit_7"},
	x18_sound_9  = {"ambient\\x18\\x18_footsteps_2"},
	x18_sound_10 = {"ambient\\x18\\x18_move_4"},
	x18_sound_11 = {"ambient\\x18\\x18_footsteps"},
	x18_sound_12 = {"ambient\\x18\\x18_move_3"},
	x16_engine1_run  = {"ambient\\x16\\x16_engine1_run"},
	x16_engine1_stop = {"ambient\\x16\\x16_engine1_stop"},
	x16_engine2_run  = {"ambient\\x16\\x16_engine2_run"},
	x16_engine2_stop = {"ambient\\x16\\x16_engine2_stop"},
	x16_hum_2    = {"ambient\\x16\\x16_hum_2"},
	x16_switch_1 = {"ambient\\x16\\switch_1"},
	x16_switch_2 = {"ambient\\x16\\switch_2"},
	x18_firedoor    = {"anomaly\\fireball_idle"},
	mon_poltergeist = {"anomaly\\anomaly_gravy_hit1"},
	heli_explosion = {"weapons\\heli_explosion"},
	trader_door_open_start  = {"device\\door_start"},
	trader_door_close_start = {"device\\door_closing"},
	trader_door_close_stop  = {"device\\door_stop"},
	trader_door_locked      = {"device\\door_locked"},
	trader_door_unlock      = {"device\\door_servomotor"},
	wood_small_open         = {"device\\wood_small_open"},
	wood_small_close_start  = {"device\\wood_small_close_start"},
	wood_small_close_stop   = {"device\\wood_small_close_stop"},
	wood_large_open         = {"device\\wood_large_open"},
	wood_large_close_start  = {"device\\wood_large_close_start"},
	wood_large_close_stop   = {"device\\wood_large_close_stop"},
	wood_door_locked        = {"device\\door_wood_locked"},
	metal_small_open        = {"device\\metal_small_open"},
	metal_small_close_start = {"device\\metal_small_close_start"},
	metal_small_close_stop  = {"device\\metal_small_close_stop"},
	metal_small_locked      = {"device\\door_metal_small_locked"},
	cell_locked     	    = {"device\\door_cell_locked"},
	cell_open	     	    = {"device\\door_cell_open"},
	sar_replic_walk         = {"characters_voice\\scenario\\sar\\sar_replics33"},
	--/ стерео
	psy_voices  = {{"characters_voice\\scenario\\yantar\\psy_voices_1"}},
	yan_antenna = {{"characters_voice\\scenario\\yantar\\psy_voices_1"}},
}
ph_snd_themes["dj_barin_station"] = { --/#+# barin
	"mplayer\\mplayer_1",
	"mplayer\\mplayer_2",
	"mplayer\\mplayer_3",
	"mplayer\\mplayer_4",
	"mplayer\\mplayer_5",
	"mplayer\\mplayer_6",
	"mplayer\\mplayer_7",
	"mplayer\\mplayer_8",
	"mplayer\\mplayer_9",
	"mplayer\\mplayer_10",
	"mplayer\\mplayer_11",
	"mplayer\\mplayer_12",
	"mplayer\\mplayer_13",
	"mplayer\\mplayer_14",
	"mplayer\\mplayer_15"
}

--/ ------------------------------------------------------------------
--/ ЗВУКИ СТАЛКЕРОВ
--/ ------------------------------------------------------------------
local sounds_base = stalker_ids.sound_script + 10000
--/ ----------------------------------------------
--/ theme functions
--/ ----------------------------------------------
function id()
	sounds_base = sounds_base + 1
	return sounds_base - 1 --/>
end

function weather_types(avail_types, npc)
	if level.rain_factor() < 0.07 then
		return "weather_good" --/>
	end
	return "weather_bad" --/>
end

function combat_types(avail_types, npc)
	if npc:best_enemy() or npc:best_danger() then
		return "" --/>
	end
	return "state" --/>
end
--/ ----------------------------------------------
theme = {
--/ ----------------------------------------------
	--/ погода
	weather = { exec = this.weather_types,
	           types = {weather_bad  = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	                    weather_good = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}} }},
	--/ состояния тела
	state = { exec = this.combat_types,
	         types = {state = {min_snd = 60, max_snd = 90, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}} }},
	--/ --------------
	sleep             = {min_snd = 10, max_snd = 15, rnd = 75, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	--/ просьба о помощи
	help              = {min_snd = 3, max_snd =  5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	help_see          = {min_snd = 5, max_snd = 10, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	help_see_tutor    = {min_snd = 3, max_snd =  5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	help_heavy        = {min_snd = 5, max_snd = 10, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	help_thanx        = {min_snd = 30, max_snd =  50, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	wounded_psy       = {min_snd = 3, max_snd =  5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	wounded_psy_shoot = {min_snd = 3, max_snd =  5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	--/ окрик
	hail              = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	--/ ожидание
	wait              = {min_snd = 7, max_snd = 10, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	--/ пїЅпїЅпїЅпїЅпїЅ пїЅпїЅпїЅ
	see_artefact      = {min_snd = 3, max_snd = 5, rnd = 100, prior = 10, rnd_id = id(), into_id = id(), max_ids = {}},
	--/ speech
	speech            = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	speech1           = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	--/ угрозы
	threat_weap       = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	threat_back       = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	threat_stop       = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	--/ реакции
	reac_see          = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	--reac_hear         = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	--reac_crps_monstr  = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	--reac_crps_enemy   = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	--reac_crps_neutral = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	--reac_crps_friend  = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	reac_nothing      = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	reac_box          = {min_snd = 1, max_snd = 2, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	reac_music        = {min_snd = 1, max_snd = 2, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	reac_joke         = {min_snd = 1, max_snd = 2, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},	
	reac_radi       = {min_snd = 3, max_snd = 4, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	--/ болтовня
	talk_hello        = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	talk_hello_friend = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	talk_bye          = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	talk_accept       = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	talk_reject       = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	talk_abuse        = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	--/ реакции на юзание
	use_yes_fight     = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	use_yes_sleep     = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	use_yes_kamp      = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	use_yes_default   = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	use_no_fight      = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	use_no_sleep      = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	use_no_weapon     = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	use_no_default    = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	use_abuse         = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	--/ бой
	fight_attack         = {min_snd = 1, max_snd = 6, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	zombied_fight_attack = {min_snd = 5, max_snd = 10,rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	fight_search         = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	fight_enemy          = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	--/ торговля
	trade_yes         = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	trade_no          = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	--/ игра на губной гармошке
	intro_music       = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	harmonica         = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	--/ игра на гитаре
	guitar            = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	--/ шутки, прибаутки
	intro_joke        = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	joke              = {min_snd = 3, max_snd = 5, rnd = 25, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	--/ истории
	story_01          = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {},
	  depence = { [2] = {theme = "story_reac_cool_info", min = 1, max = 1},
	              [3] = {theme = "story_reac_continue",  min = 2, max = 3},
	              [5] = {theme = "story_reac_laughter", type = "all"}}},
	story_02          = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {},
	  depence = { [2] = {theme = "story_reac_yes",          min = 1, max = 2},
	              [3] = {theme = "story_reac_continue",     min = 1, max = 1},
	              [4] = {theme = "story_reac_action_right", min = 1, max = 1},
	              [5] = {theme = "story_reac_cool_teller",  min = 1, max = 1},
	              [6] = {theme = "story_reac_continue",     min = 1, max = 1},
	              [7] = {theme = "story_reac_belief_story, story_reac_final_happy, story_reac_yes", min = 2, max = 4}}},
	story_03          = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {},
	  depence = { [1] = {theme = "story_reac_continue", min = 1, max = 1},
	              [2] = {theme = "story_reac_final_tragic", min = 1, max = 1},
	              [3] = {theme = "story_reac_belief_story", min = 2, max = 3}}},
	story_04          = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {},
	  depence = { [1] = {theme = "story_reac_continue", min = 1, max = 1},
	              [2] = {theme = "story_reac_final_tragic", min = 1, max = 1},
	              [3] = {theme = "story_reac_belief_story", min = 2, max = 3}}},
	story_05          = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {},
	  depence = { [1] = {theme = "story_reac_advice_sceptic, story_reac_advice_support", min = 1, max = 1}}},
	story_06          = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {},
	  depence = { [2] = {theme = "story_reac_continue", min = 1, max = 1},
	              [3] = {theme = "story_reac_cool_teller", min = 1, max = 1},
	              [4] = {theme = "story_reac_action_right", min = 1, max = 1},
	              [5] = {theme = "story_reac_yes", min = 1, max = 1},
	              [6] = {theme = "story_reac_disbelief_teller, story_reac_belief_story", min = 2, max = 3},
	              [7] = {theme = "story_reac_cool_teller", min = 1, max = 1},
	              [8] = {theme = "story_reac_wonder", min = 1, max = 1},
	              [9] = {theme = "story_reac_disbelief_story, story_reac_belief_story, story_reac_yes", min = 2, max = 4}}},
	legend_01         = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {},
	  depence = { [1] = {theme = "story_reac_doubt", min = 1, max = 1},
	              [2] = {theme = "story_reac_wonder, story_reac_disbelief_story", min = 1, max = 1},
	              [3] = {theme = "story_reac_yes", min = 2, max = 3},
	              [4] = {theme = "story_reac_yes, story_reac_belief_story", min = 2, max = 4}}},
	legend_02         = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {},
	  depence = { [1] = {theme = "story_reac_doubt", min = 1, max = 1},
	              [2] = {theme = "story_reac_disbelief_story", min = 1, max = 1},
	              [3] = {theme = "story_reac_wonder", min = 1, max = 1},
	              [4] = {theme = "story_reac_laughter", min = 1, max = 1},
	              [5] = {theme = "story_reac_yes, story_reac_belief_story", min = 2, max = 4}}},
	legend_03         = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {},
	  depence = { [1] = {theme = "story_reac_cool_info", min = 1, max = 1},
	              [2] = {theme = "story_reac_yes, story_reac_doubt", min = 2, max = 4}}},
	legend_04         = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {},
	  depence = { [1] = {theme = "story_reac_fear", min = 1, max = 1},
	              [2] = {theme = "story_reac_yes, story_reac_belief_story", min = 2, max = 4}}},
	legend_05         = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {},
	  depence = { [1] = {theme = "story_reac_yes", min = 2, max = 3},
	              [2] = {theme = "story_reac_doubt", min = 1, max = 1},
	              [3] = {theme = "story_reac_disbelief_story, story_reac_belief_story", min = 2, max = 4}}},
	
	story_reac_action_right     = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_action_wrong     = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_advice_sceptic   = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_advice_support   = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_belief_story     = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_continue         = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_cool_info        = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_cool_teller      = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_disbelief        = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_disbelief_story  = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_disbelief_teller = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_doubt            = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_fear             = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_final_happy      = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_final_tragic     = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_laughter         = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_old_story        = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_uncertain        = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_wonder           = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	story_reac_yes              = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	soldiers_backoff  = {min_snd = 1, max_snd = 3, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},

	--/ УНИКАЛЬНЫЕ ТЕМЫ ----------------------------
	--/ Escape
	esc_tolik_help      = {min_snd = 7, max_snd = 10, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_guard_camp      = {min_snd = 7, max_snd = 10, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_factory_raid    = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_factory_attack  = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_factory_victory = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_factory_go      = {min_snd = 3, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_fox_alert       = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_tolik_to_wolf   = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_tolik_to_lager  = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_tolik_thanks    = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_wolf_thanks     = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_wolf_say_thanks = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_lager_killer    = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_fanat_dialog    = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_fanat_ready     = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_direction_fire  = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_bridge_soldiers = {min_snd = 10, max_snd = 25, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_bandit_shustryi = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_shustryi_help   = {min_snd = 5, max_snd = 15, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_wolf_radio      = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_wolf_radio_1    = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_petruha_raport  = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_petruha_raport_radio = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_petruha_call    = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_fox_thanks      = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_shustryi_thanks = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_assault_raid    = {min_snd = 16, max_snd = 25, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_merc_dialog1    = {min_snd = 1, max_snd = 3, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_merc_dialog2    = {min_snd = 1, max_snd = 3, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_merc_dialog3    = {min_snd = 1, max_snd = 3, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_merc_dialog4    = {min_snd = 1, max_snd = 3, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_merc_dialog5    = {min_snd = 1, max_snd = 3, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_merc_dialog6    = {min_snd = 1, max_snd = 3, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_merc_dialog7    = {min_snd = 1, max_snd = 3, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	esc_merc_dialog8    = {min_snd = 1, max_snd = 3, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	--/ Garbage DramMoment
	gar_dm_bandit_backoff1  = {min_snd = 5, max_snd = 8, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	gar_dm_bandit_backoff2  = {min_snd = 5, max_snd = 8, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	gar_dm_bandit_demand    = {min_snd = 8, max_snd = 10, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	gar_dm_newbie_no_money  = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	gar_dm_newbie_help_me   = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	gar_dm_newbie_thank_you = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	gar_hellcar_alarm     = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	gar_hellcar_ambush    = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	gar_bandits_seryi     = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	gar_grey_grey         = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	gar_seryi_see_actor   = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	gar_dolg_blokpost     = {min_snd = 10, max_snd = 25, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	gar_direction_fire    = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	gar_hellcar_to_battle = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	gar_hellcar_victory   = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	gar_seriy_thanks_help = {min_snd = 16, max_snd = 25, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	--/ DarkValley
	val_prisoner_captive_help_me   = {min_snd = 6, max_snd = 10, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_prisoner_captive_come_here = {min_snd = 4, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_prisoner_captive_open      = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_prisoner_captive_thanx     = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_rob_leader_call            = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_rob_leader_jeer            = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_rob_guard_jeer             = {min_snd = 6, max_snd = 10, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	--val_gate_soldiers              = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	--val_chase_soldiers             = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	--val_opendoor_soldier           = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_escort_guards              = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_escort_captive_phrase1     = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_escort_captive_phrase2     = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_escort_captive_phrase3     = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_escort_nap1_phrase1        = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_escort_nap1_phrase2        = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_escort_nap1_phrase3        = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_escort_nap1_phrase4        = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_escort_nap1_phrase5        = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_escort_nap1_phrase6        = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_escort_nap1_phrase7        = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_escort_dead                = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_escort_nap1_go_home        = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_escort_phrase_invite       = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_guard					   = {min_snd = 10, max_snd = 25, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	val_trader_whistle			   = {min_snd = 10, max_snd = 25, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	--/ dolina
	dolina_drunk_bandit       = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	dolina_drunk_bandit_vomit = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	dol_informer_boss_call	  = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	--/ DarkScape
	ds_leader_greet           = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	--/ DeadCity
	cit_doctor_start_dlg          = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	cit_doctor_end_dlg            = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	cit_jail_guard_sneer          = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	cit_base_guard                = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	cit_base_guard_talk_to_actor2 = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	cit_jail_guard_sleep          = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	cit_doctor_dlg1 = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	cit_doctor_dlg2 = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	cit_doctor_dlg3 = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	cit_doctor_dlg4 = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	cit_doctor_dlg5 = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	cit_doctor_dlg6 = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	cit_doctor_dlg7 = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	cit_colonel_dlg1 = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	cit_colonel_dlg2 = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	cit_colonel_dlg3 = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	cit_colonel_dlg4 = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	cit_colonel_dlg5 = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	--/ Agroprom
	agr_factory_soldiers		= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	--/ desertir
	agr_dont_shoot     = {min_snd = 5, max_snd = 10, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	agr_desertir_spam  = {min_snd = 5, max_snd = 10, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	agr_stalker_help_1 = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	agr_stalker_help_2 = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	agr_stalker_help_3 = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	agr_stalker_help_4 = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	agr_krot_thanks_1  = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	agr_krot_thanks_2  = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	agr_krot_fear      = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	agr_doctor_1       = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	--/ Radar
	rad_replics1   = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	rad_replics2   = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	rad_replics3   = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	rad_replics4   = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	rad_replics5   = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	rad_replics6   = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	rad_replics7   = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	rad_replics8   = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	rad_replics9   = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	rad_replics_10 = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	rad_replics_11 = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	rad_replics_12 = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	rad_replics_13 = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	rad_replics_14 = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	rad_heil1      = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	rad_heil2      = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	rad_heil3      = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	rad_move_on    = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	--/ Bar Rostok Duty Guards
	bar_dolg_base_guard_backoff = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bar_dolg_base_guard_no_talk = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bar_bar_osvedomitel_hello   = {min_snd = 15, max_snd = 15, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bar_bar_barmen_hello        = {min_snd = 2, max_snd = 15, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bar_bar_barmen_hello_room   = {min_snd = 10, max_snd = 15, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bar_dolg_leader_hello       = {min_snd = 10, max_snd = 15, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bar_replics0 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bar_replics1 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bar_replics2 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	--/ Bar dolg guard
	bar_dolg_guard_stop = {min_snd = 15, max_snd = 20, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bar_guard_prohodi   = {min_snd = 7, max_snd = 20, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bar_dolg_guard_busy = {min_snd = 7, max_snd = 20, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	--/ Bar dolg hangar bridge
	bar_dolg_hangar_bridge_hello = {min_snd = 16, max_snd = 25, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bar_guard_enter = {min_snd = 6, max_snd = 10, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bar_guard_stop  = {min_snd = 6, max_snd = 10, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	--/ Bar dolg Petrenko
	bar_dolg_petrenko_hello = {min_snd = 3, max_snd = 15, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	--/ Bar psyh
	bar_psycho_pain     = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bar_psycho_goodluck = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bar_barman_psycho   = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bar_arena_public    = {min_snd = 5, max_snd = 7, rnd = 80, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	--/ Rostok volkodav
	rostok_volkodav_talk_1						= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},      
	rostok_volkodav_talk_2						= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	rostok_volkodav_assistant_talk_1			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	rostok_volkodav_assistant_talk_2			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	rostok_volkodav_assistant_talk_3			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	--/ Rostok kruglov
	rostok_kruglov_help_1                       = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	rostok_kruglov_help_2                       = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	rostok_kruglov_help_3                       = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	rostok_kruglov_help_4                       = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	rostok_kruglov_help_5                       = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	rostok_kruglov_help_6                       = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
    rostok_kruglov_torrid                       = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	kruglov_stop_enemy_1                        = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	kruglov_stop_enemy_2                        = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	--/ rostok factor
	rosf_fake_actor								= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	--/ yantar sounds
	yantar_professor_idle						= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_professor_to_kruglov_1				= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_professor_to_kruglov_2				= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_kruglov_to_professor_1				= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_kruglov_to_professor_2				= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_kruglov_to_actor						= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_dream_talk_1							= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_dream_talk_2							= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_dream_talk_3							= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_professor_talk_1						= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_professor_radiation_quest_1			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_professor_radiation_quest_2			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_kruglov_radiation_quest_1			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_kruglov_radiation_quest_2			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_kruglov_radiation_quest_3			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_kruglov_radiation_quest_4			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_kruglov_radiation_quest_5			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_kruglov_radiation_quest_6			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_kruglov_radiation_quest_7			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_kruglov_radiation_quest_8			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_kruglov_radiation_quest_9			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_kruglov_radiation_quest_10			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_professor_brain_quest_bad_1			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_professor_brain_quest_bad_2			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_professor_brain_quest_good_1			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_professor_brain_quest_good_2			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_professor_brain_quest_good_3			= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_probe_1								= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_probe_2								= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_probe_3								= {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yantar_eco_gate_warn						= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	yan_rifle_dude_cry  						= {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	test_mega_remark = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	--/ Brainlab sounds
	brainlab_system_message_1 = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	brainlab_system_message_2 = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	brainlab_system_message_3 = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	brainlab_system_message_4 = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	brainlab_system_message_5 = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	--/ Military sounds
	mil_max_thanx                  = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_max_before_collect         = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_kolyan                     = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_max_to_kolyan              = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_max_to_tolyan              = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_collect_laugh1             = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_collect_laugh2             = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_collect_laugh3             = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_collect_laugh4             = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_collect_laugh5             = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_collect_phrase1            = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_collect_phrase2            = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_collect_phrase3            = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_collect_phrase4            = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_collect_phrase5            = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_collect_phrase6            = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_collect_phrase7            = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_dolg_about_sniper          = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_dolg_go_attack             = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_freedom_patrol             = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_dolg_after_kill1           = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_dolg_after_kill2           = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_dolg_after_kill3           = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_freedom_zoneguard          = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_freedom_patrol_base        = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_max_khutor_attack          = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_guard_to_max               = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_lukash_to_guard            = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_lukash_to_actor            = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_paul_frost                 = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_dolg_killer                = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_dolg_scull                 = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_max_to_actor               = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_collect_phrases            = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_pavlik_to_ara              = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_ara_to_pavlik              = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_ara_ambush                 = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_hunter1                    = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_hunter2                    = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_hunter3                    = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_dolg_getready              = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_dolg_lukash_done           = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_freedom_ambush1            = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_freedom_ambush2            = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_freedom_ambush3            = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_freedom_ambush4            = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_freedom_ambush5            = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_freedom_ambush6            = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_freedom_victory1           = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_freedom_victory2           = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_freedom_victory3           = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_freedom_victory4           = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_freedom_victory5           = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_dolg_before_attack1        = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_dolg_before_attack2        = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_dolg_fight                 = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_dolg_silent                = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_cherep_hi                  = {min_snd = 1, max_snd = 3, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_mercs_dialog               = {min_snd = 1, max_snd = 3, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_contact_wounded            = {min_snd = 1, max_snd = 3, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_mercs_dialog1              = {min_snd = 1, max_snd = 3, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_mercs_dialog2              = {min_snd = 1, max_snd = 3, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_mercs_dialog3              = {min_snd = 1, max_snd = 3, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_mercs_dialog4              = {min_snd = 1, max_snd = 3, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_mercs_dialog5              = {min_snd = 1, max_snd = 3, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_mercs_dialog6              = {min_snd = 1, max_snd = 3, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_ahaha                      = {min_snd = 1, max_snd = 3, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_assistance                 = {min_snd = 1, max_snd = 3, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_crazy                      = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_crazy_caution              = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_hurry_up              	   = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	--/ Pripyat sounds
	pripyat_pri_radiation_quest_1  = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	pripyat_pri_radiation_quest_2  = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	pripyat_pri_radiation_quest_3  = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	pripyat_pri_radiation_quest_4  = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	pripyat_pri_radiation_quest_5  = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	pripyat_pri_radiation_quest_6  = {min_snd = 1, max_snd = 1, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	pri_followers_leader_phrase1_1 = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	pri_followers_leader_phrase1_2 = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	pri_followers_leader_phrase1_3 = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	pri_followers_final_phrase1    = {min_snd = 3, max_snd = 5, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	pri_followers_final_phrase2    = {min_snd = 6, max_snd = 9, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	--/ bunker sounds
	bun_hat_lab  = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bun_replics1 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bun_replics2 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bun_replics3 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bun_replics4 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bun_replics5 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bun_replics6 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bun_replics7 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bun_replics8 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bun_replics9 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bun_replics10 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	--/ darklab sounds
	dar_replics1 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	dar_replics2 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	dar_replics3 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	dar_replics4 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	dar_replics5 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	dar_replics6 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	dar_replics7 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	dar_replics8 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	dar_replics9 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	dar_replics10 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	dar_replics11 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	dar_replics12 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	dar_replics13 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	dar_replics14 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	dar_replics15 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	dar_replics16 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	dar_replics10_x1 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	dar_replics10_x2 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	dar_replics17 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	dar_replics18 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	dar_replics19 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	dar_replics20 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	dar_replics21 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	dar_replics22 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	dar_replics23 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	dar_replics24 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	dar_replics25 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	dar_replics26 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	dar_replics27 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	dar_replics28 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	dar_replics29 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	dar_replics30 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	dar_replics31 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	dar_replics32 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	dar_whisp1    = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	dar_whisp2    = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	dar_petrenko  = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	ghost_scary = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	ghost_hell  = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	--/ basement sounds
	bas_replics1 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bas_replics2 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bas_replics3 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bas_replics4 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bas_replics5 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bas_replics6 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bas_replics7 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bas_replics8 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bas_replics9 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bas_replics10 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bas_replics11 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bas_replics12 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bas_replics13 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bas_replics14 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bas_replics_way = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bas_replics_take_a_look = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bas_replics_ghost1 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bas_replics_ghost2 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bas_replics15 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bas_replics16 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bas_replics17 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bas_replics18 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bas_replics19 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bas_replics20 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bas_replics21 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bas_replics22 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bas_replics23 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bas_replics24 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bas_replics25 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bas_replics26 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bas_replics27 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bas_replics28 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bas_replics29 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bas_replics30 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bas_replics31 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bas_replics32 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bas_replics33 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bas_replics34 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bas_replics35 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bas_replics36 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bas_replics37 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bas_replics38 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bas_replics39 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bas_replics40 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bas_holo_death = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	bas_holo_threat = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	--/ x16 sounds
	x16_brain1 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_brain2 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_brain3 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_brain4 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_brain5 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_flash = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_notification = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_meet	 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics2 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics3 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics4 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics5 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics6 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics7 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics8 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics9 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics10 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics11 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics11f = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics12 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics13 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics14 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics15 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics16 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics17 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics18 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics19 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics20 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics21 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics22 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics23 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics24 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics25 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics26 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics27 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics28 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics29 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics30 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics31 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics32 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics33 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics34 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics35 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics36 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics37 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics38 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics39 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics40 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics41 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics42 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics43 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics44 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics45 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	x16_replics46 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	--/ swamp
	swa_replics1 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	swa_replics2 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	swa_replics3 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	swa_replics4 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	swa_replics5 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	--/ stancia
	sta_replics1 	= {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sta_replics2	= {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sta_replics3 	= {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sta_replics4 	= {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sta_replics5 	= {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sta_open_gates 	= {min_snd = 6, max_snd = 9, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sta_ambush 		= {min_snd = 6, max_snd = 9, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sta_fall_back	= {min_snd = 6, max_snd = 9, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	--/ generators
	gen_dram_moment = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	gen_fall = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	gen_ghost_bunker = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	gen_ghost_scene = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	gen_ghost_welcome = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	gen_gul = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	gen_psi = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	gen_zov = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	--/ oso
	oso_replics1  = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_replics2  = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_replics3  = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_replics4  = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_replics5  = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_replics6  = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_replics7  = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_replics8  = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_replics9  = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_replics10  = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_replics11  = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_replics12  = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_replics13  = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_replics14  = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_replics15  = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_replics16  = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_replics17  = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_replics17a  = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_replics17b  = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_replics17c  = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_teleport   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_silence   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_final1 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_final2 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_final3 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_final4 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_final5 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_final6 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_final7 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_final8 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_final9 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_final10_main = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_final11_main = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_final11h_main = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_final12_main = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_final13_main = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_final14_main = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_final15_main = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_final16_main = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_final17_main = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_final18_main = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_final19_main = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_final20_main = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_final21_main = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_final22_main = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_final23 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_final24 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_final25 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	oso_final26 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	--/ sarcofag
	sar_replics1   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sar_replics2   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sar_replics2a = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sar_replics3   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sar_replics4   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sar_replics5   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sar_replics6   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sar_replics7   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sar_replics8   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sar_replics9   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sar_replics10   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sar_replics11   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sar_replics12   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sar_replics13   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sar_replics14   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sar_replics15   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sar_replics16a   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sar_replics16b   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sar_replics17   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sar_replics18   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sar_replics18d  = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sar_replics18f  = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sar_replics19   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sar_replics20   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sar_replics21   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sar_replics22   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sar_replics23   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sar_replics24   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sar_replics25   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sar_replics26   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sar_replics27   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sar_replics28   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sar_replics29   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sar_replics30   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sar_replics31   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sar_replics32   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sar_replics33   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sar_replics34   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sar_replics35   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sar_replics36   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sar_replics37   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sar_replics38   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sar_replics39   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sar_replics40   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sar_replic_walk = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	sar_replic_walk = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	--/ warlab
	war_thing0 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_thing1 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_thing2 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_thing3 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_thing4 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_thing5 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_thing6 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_thing7 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_thing8 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_thing9 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_thing10 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics1 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics2 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics3 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics4 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics5 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics6 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics7 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics8 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics9 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics10 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics11 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics12 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics13 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics14 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics15 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics16 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics17 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics18 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics19 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics20 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics21 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics22 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics23 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics24 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics25 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics26 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics27 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics28 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics29 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics30 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics31 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics32 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics33 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics34 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics35 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics36 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics37 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics38 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics39 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics40 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics40a = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics41 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics42 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics43 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics44 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics45 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics46 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics47 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics48 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics49 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics50 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics51 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics52 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	war_replics53 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	--/ outskirts
	out_chef_replic     = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	out_guard_replic1   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	out_guard_replic2   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	out_guard_replic3   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	out_guard_replic4   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	out_guard_replic5   = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	out_drunken_replic1 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	out_drunken_replic2 = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	out_dialog1     = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	out_dialog2 		= {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	out_dialog3 		= {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	out_dialog4 		= {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	out_dialog5 		= {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	out_dialog6 		= {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	out_dialog7 		= {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	out_dialog8 		= {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	out_dialog9 		= {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	out_dialog10 		= {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	out_dialog11 		= {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	out_bar_cough1 		= {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	out_bar_sing1 		= {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	out_bar_sing2 		= {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	out_bar_sing3 		= {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	out_bar_sing4		= {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	out_bar_whistle1 	= {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	out_bar_whistle2 	= {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	--/ forgotten
	forg_dolg_battle = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	--/ darkscape
	ds_sin_leader_shoot = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	--/ country
	con_actor_scene_1  = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	con_blowout_voices = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	
	--/ freeplay
	mil_suicide_cry     = {min_snd = 6, max_snd = 9, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_controller_call = {min_snd = 5, max_snd = 7, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
	mil_suicide_shot    = {min_snd = 6, max_snd = 9, rnd = 100, prior = 5, rnd_id = id(), into_id = id(), max_ids = {}},
}


--/ -----------------------------------------------------------------------------------------------
actor_theme = { --/ в темах для игрока интервал задается в миллисекундах!!!
--/ -----------------------------------------------------------------------------------------------
	level_border_detector = {min_snd = 10, max_snd = 100, sounds = {
		xr_sound.get_safe_sound_object("detectors\\geiger_1"),
		xr_sound.get_safe_sound_object("detectors\\geiger_1"),
		xr_sound.get_safe_sound_object("detectors\\geiger_1"),
		xr_sound.get_safe_sound_object("detectors\\geiger_1"),
		xr_sound.get_safe_sound_object("detectors\\geiger_2"),
		xr_sound.get_safe_sound_object("detectors\\geiger_2"),
		xr_sound.get_safe_sound_object("detectors\\geiger_4"),
		xr_sound.get_safe_sound_object("detectors\\geiger_5"),
		xr_sound.get_safe_sound_object("detectors\\geiger_6")
	}}
}

--/ -----------------------------------------------------------------------------------------------
--/ Process (функции)
--/ -----------------------------------------------------------------------------------------------
local default_prefix = "characters_voice\\"
local character_prefix = ""

function check_prefix(s)
	local flag = string.sub(s, 1, 1)
	return flag, string.sub(s, 3)
end

function select_sound_from_ltx(obj, section, ltx)
	--/[1] проверка по story_id
	local p = tostring( obj:story_id() )
	if p ~= "nil" and ltx:line_exist(section, p) then
		return ltx:r_string(section, p)
	end
	--/[2] проверка по npc_profile
	p = obj:profile_name()
	if p and ltx:line_exist(section, p) then
		return ltx:r_string(section, p)
	end
	--/[3] проверка по character_community
	p = obj:character_community()
	if p and ltx:line_exist(section, p) then
		return ltx:r_string(section, p)
	end
	--/[4] npc sdk name
	p = obj:name()
	if p and ltx:line_exist(section, p) then
		--[[if ltx:line_exist("infos", p) then
			local cond = ltx:r_string("infos", p)
			if has_info(cond) then
				return nil
			end
		end--]]
		return ltx:r_string(section, p)
	end
	--/[5] загрузка дефолта
	if ltx:line_exist(section, "stalker") then
		return ltx:r_string(section, "stalker")
	end
	return nil
end

function load_sound(obj)
	local obj_id = obj:id()
	--/ функция загрузки звуков на основе данных из ltx (snd_ini)
	load_sound_from_ltx = function(obj, field, tbl)
		tbl.max_ids[obj_id] = {}
		if snd_ini:section_exist(field.."_rnd") then
			local s = select_sound_from_ltx(obj, field.."_rnd", snd_ini)
			if s then
				local flag, path = check_prefix(s)
				if flag == "0" then
					character_prefix = obj:sound_prefix()
					obj:sound_prefix(default_prefix)
				end
				tbl.max_ids[obj_id].rnd_max = obj:add_sound(path, nstl, snd_type.talk, sound_priority, sound_mask, tbl.rnd_id)
		--		log("load_sound_from_ltx: obj=[%s] flag=[%s] prefix=[%s] path=[%s] rnd_max=[%d]:(%s)", obj:name(), flag, obj:sound_prefix(), path, tbl.max_ids[obj_id].rnd_max, "rnd") --/#~#
				if flag == "0" then
					obj:sound_prefix(character_prefix)
				end
			end
		end
		if snd_ini:section_exist(field.."_seq") then
			local s = select_sound_from_ltx(obj, field.."_seq", snd_ini)
			if s then
				local flag, path = check_prefix(s)
				if flag == "0" then
					character_prefix = obj:sound_prefix()
					obj:sound_prefix(default_prefix)
				end
	--			log("load_sound_from_ltx: obj=[%s] flag=[%s] prefix=[%s] path=[%s] :(%s)", obj:name(), flag, obj:sound_prefix(), path, "seq") --/#~#
				tbl.max_ids[obj_id].into_max = obj:add_sound(path, nstl, snd_type.talk, sound_priority, sound_mask, tbl.into_id)
				tbl.max_ids[obj_id].into_cycled = true
				if flag == "0" then
					obj:sound_prefix(character_prefix)
				end
			end
		end
		if snd_ini:section_exist(field.."_single") then
			local s = select_sound_from_ltx(obj, field.."_single", snd_ini)
			if s then
				local flag, path = check_prefix(s)
				if flag == "0" then
					character_prefix = obj:sound_prefix()
					obj:sound_prefix(default_prefix)
				end
--				log("load_sound_from_ltx: obj=[%s] flag=[%s] prefix=[%s] path=[%s] :(%s)", obj:name(), flag, obj:sound_prefix(), path, "single") --/#~#
				tbl.max_ids[obj_id].into_max = obj:add_sound(path, nstl, snd_type.talk, sound_priority, sound_mask, tbl.into_id)
				tbl.max_ids[obj_id].into_cycled = false
				if flag == "0" then
					obj:sound_prefix(character_prefix)
				end
			end
		end
	end
	--/<
	load_sound_themes = function(obj, tbl)
		for k,v in pairs(tbl) do
			if v.types then
				load_sound_themes(obj, v.types) --/> рекурсивный вызов
			else
				load_sound_from_ltx(obj, k, v)
			end
		end
	end
	--/<
	load_sound_themes(obj, theme)
	--/ делаем заготовку в db.sound
	db.sound[obj_id] = {}
--	log("load_sound_from_ltx: loaded for obj=[%s]/[%s] prefix=[%s]", obj:name(), obj:section(), obj:sound_prefix(), "") --/#~#
	--table.print(theme, sModule..":Theme|"..obj:name()) --/#~#
end
--/ ------------------------------------------------------------------------------------------------