--[[-----------------------------------------------------------------------------------------------
 File       : tasks_secret_lab.script
 Description: Tasks secret_lab
 Copyright  : 2010 © LA-team
 Author     : vintar
 Editors    : vintar(27.06.2012) lox(12.02.2013)
 Last edit  : 23.06.18 (tomilovsenya) – fixed PDA messages
--]]-----------------------------------------------------------------------------------------------

--/------------------------------------------------------------------
--/ VARIABLEs
--/------------------------------------------------------------------
local sModule = script_name() --/ string name of the file module
--/ -----------------------------------------------------------------
--/ print-log (output of the debug information)
--/ -----------------------------------------------------------------
local log = function(fmt,...) _G.log(sModule..":"..tostring(fmt),...) end
--/ -----------------------------------------------------------------

--/ -----------------------------------------------------------------------------------------------
--/ General process
--/ -----------------------------------------------------------------------------------------------
function proceed(obj, sEvent)
	if db.sMapNow == "la14u_secret_lab" then
		if not has_info("secret_actor_reached_level")
		  and (has_info("rosf_actor_reached_level") or has_info("rosf_duty_suckers_start"))
			then
			give_info("secret_actor_reached_level")
		end
	end
	if sEvent == "item_take" then
		if obj:story_id() == 6600 then
			give_info("secret_documents_have")
		elseif obj:story_id() == 6601 then
			if not has_info("secret_pda_have") then
				give_info("secret_pda_have")
			end
		end
	end
end

function process_info_portion(info_id)
	if info_id == "secret_pda_have" then
		news_manager.send_tip_hud(game.translate_string("scientist_dead_header"), game.translate_string("secret_pda_message"), "codedoor")
		local snd = xr_sound.get_safe_sound_object("characters_voice\\scenario\\sec\\secret_scientist")
		snd:play(db.actor, 1, sound_object.s2d)
		return true --/>
	end
	if info_id == "sec_scene_view" then
		local pos = get_patrol("secret_scene_view"):point(0)
		db.actor:set_actor_look_at_position(pos, 0)
		return true --/>
	end
	return false --/>
end
--/ -----------------------------------------------------------------
--/ Process
--/ -----------------------------------------------------------------

--/ -----------------------------------------------------------------------------------------------